version: '3'

services:
  database:
    container_name: "uni_diploma"
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
#    networks:
#      - "common_net_inf"

#networks:
#  common_net_inf:
#    external:
#      name: "common_net_inf"